nocmd:cmd_07390

#!capable_backup: backupメール通知
#!capable_backup: vrrp
#!capable_backup: ネットワーク/pp/lan/tunnel等backupによりvpn/イーサネット/isdn
#!capable_backup: フローティングスタティック
#!capable_dynamicfilterssessionsmax: 40000
#!capable_intll2switch: no
#!capable_ipkeepaliveremotemax: 1000
#!capable_lanmanagement: no
#!capable_log: syslogでのoutput
#!capable_log: メモリに蓄積
#!capable_log: リブートlog保存
#!capable_log記憶容量: 500lines
#!capable_managementprotocol: snmp
#!capable_pppoesessionsmax: 16
#!capable_programmanagement: tftpによるupdate
#!capable_programmanagement: コンフィグ多重
#!capable_tagvlanieee802.1q: 32idperlan
#!capable_セキュリティー: dhcp端末auth
#!capable_セキュリティー: macaddressfiltering
#!capable_セキュリティー: urlfiltering
#!capable_セキュリティー: winnyフィルター
#!capable_デフォルトIPアドレス no
#!capable_外形寸法 445
#!capable_拡張 no
#!capable_最大消費電力(皮相電力)、最大消費電流、発熱量1 30w
#!capable_最大消費電力(皮相電力)、最大消費電流、発熱量2 0.3a
#!capable_最大消費電力(皮相電力)、最大消費電流、発熱量3 108kj/h
#!capable_仕様対象ファームウェア rev.9.00.60
#!capable_質量(付属品含まず) 4.0kg
#!capable_省エネ 未使用lanのシャットダウン
#!capable_状態表示ランプ1 前面,10
#!capable_状態表示ランプ2 背面,0
#!capable_電源: 3極プラグ
#!capable_電源: ac100v
#!capable_電源: powerスイッチ
#!capable_電源: power内蔵
#!capable_電波障害規格、環境負荷物質管理1 vcciクラスa
#!capable_電波障害規格、環境負荷物質管理2 rohscapable_
#!capable_電話 no
#!capable_統計・management: no
#!capable_動作環境条件1 周囲温度0～40℃
#!capable_動作環境条件2 周囲湿度15～80%
#!capable_筐体 ファン,1基
#!capable_筐体 金属筐体
#!capable_筐体内温度測定 温度計内蔵
#auth.chap: yes
#auth.isdnid: yes,optional:isdn
#auth.pap: yes
#auth.radius: yes
#compression.ccp: yes
#compression.ipcomp: yes
#compression.vjc: yes
#confvia.console: yes
#confvia.dataconnect: yes
#confvia.isdn: yes
#confvia.sshserver: yes
#confvia.telnetclient: yes
#confvia.telnetserver: yes
#confvia.tftp: yes
#conn.adsl: yes
#conn.atm: yes
#conn.catv: yes
#conn.dataconnect: yes
#conn.ftth: yes
#conn.ipv6.dual: yes
#conn.ipv6.ipoe: yes
#conn.ipv6.native: yes
#conn.ipv6.pppoe: yes
#conn.ipv6.raproxy: yes
#conn.ipv6.tunnel: yes
#conn.ip-vpn: yes
#conn.isdn: yes,optional:isdn
#conn.leased-line: yes
#conn.mp: yes,optional:isdn
#conn.ntt-flets: yes
#conn.ppp: yes
#conn.pppoe: yes
#conn.wide-ether: yes
#firewall.ipv4.filter.dynamic.tcp: yes
#firewall.ipv4.filter.dynamic.udp: yes
#firewall.ipv4.filter.dynamic.ftp: yes
#firewall.ipv4.filter.dynamic.tftp: yes
#firewall.ipv4.filter.dynamic.domain: yes
#firewall.ipv4.filter.dynamic.www: yes
#firewall.ipv4.filter.dynamic.smtp: yes
#firewall.ipv4.filter.dynamic.pop3: yes
#firewall.ipv4.filter.dynamic.telnet: yes
#firewall.ipv4.filter.dynamic.netmeeting: yes
#firewall.ipv4.filter.static.ipaddress: yes
#firewall.ipv4.filter.static.port: yes
#firewall.ipv4.filter.static.protocol: yes
#firewall.ipv4.filter.static.state: yes
#firewall.ipv4.filter.static.source: yes
#firewall.ipv4.filter.static.destination: yes
#firewall.ipv4.ids.ip: yes
#firewall.ipv4.ids.ip-option: yes
#firewall.ipv4.ids.fragment: yes
#firewall.ipv4.ids.icmp: yes
#firewall.ipv4.ids.udp: yes
#firewall.ipv4.ids.tcp: yes
#firewall.ipv4.ids.ftp: yes
#firewall.ipv4.ids.winny: yes
#firewall.ipv4.ids.share: yes
#firewall.ipv4.ids.default: yes
#firewall.ipv6.filter.dynamic.tcp: yes
#firewall.ipv6.filter.dynamic.udp: yes
#firewall.ipv6.filter.dynamic.ftp: yes
#firewall.ipv6.filter.dynamic.tftp: yes
#firewall.ipv6.filter.dynamic.dns: yes
#firewall.ipv6.filter.dynamic.www: yes
#firewall.ipv6.filter.dynamic.smtp: yes
#firewall.ipv6.filter.dynamic.pop3: yes
#firewall.ipv6.filter.dynamic.telnet: yes
#firewall.ipv6.filter.static.ipaddress: yes
#firewall.ipv6.filter.static.port: yes
#firewall.ipv6.filter.static.protocol: yes
#firewall.ipv6.filter.static.state: yes
#firewall.ipv6.filter.static.source: yes
#firewall.ipv6.filter.static.destination: yes
#misc.bod: yes
#misc.callback: yes
#misc.cidr: yes
#misc.dhcp.client: yes
#misc.dhcp.ra: yes
#misc.dhcp.server: yes
#misc.dns.netvolante: yes
#misc.dns.server.recursive: yes
#misc.dns.server.select: yes
#misc.filter.packetfwd: yes
#misc.filter.route: yes
#misc.heartbeat: yes
#misc.interface.lan2ndadd: yes
#misc.interface.loopback: yes
#misc.interface.null: yes
#misc.multihome: yes
#misc.ntp.client: yes
#misc.piafs: yes
#misc.proxyarp: yes
#misc.ras: yes
#misc.sntp.server: yes
#misc.taskschedule: yes
#misc.wol: yes
#natnapt.dmz: yes
#natnapt.ftp: yes
#natnapt.ipmasq.restrict:yes
#natnapt.ipmasq.standard: yes
#natnapt.ipmasq.static: yes
#natnapt.nat.standard: yes
#natnapt.nat.static: yes
#natnapt.passthrough.ipsec: yes
#natnapt.passthrough.pptp: yes
#natnapt.ping: yes
#natnapt.sessions: 40000
#natnapt.sip.conns: 200
#natnapt.sip: yes
#natnapt.traceroute: yes
#ports.console: 1
#ports.isdn.st: yes,optional:isdn
#ports.isdn.u: no
#ports.lan.100: 2
#ports.lan.1000: 2
#ports.lan.total: 4
#ports.line: no
#ports.pri: yes,optional:isdn
#ports.tel: no
#ports.usb: no
#ports.wan.isdn: yes,optional:isdn
#ports.wan.lan: any
#qos.classtype: ipaddress
#qos.classtype: protocol
#qos.classtype: tosfield
#qos.classtype: 番号
#qos.type.bandwidth: yes
#qos.type.bwdetect: yes
#qos.type.cbq: yes,optional:isdn
#qos.type.hierarchical: yes
#qos.type.loadnotify: yes
#qos.type.priority: yes
#qos.type.vpn: yes
#qos.type.wfq: yes,optional:isdn
#qos.網側qosとの連携: diffserv
#qos.網側qosとの連携: tos→cos変換
#ramrom.flashrom: 32meg
#ramrom.ram: 256meg
#routing.capable: ip,ipv6
#routing.entries: 20000
#routing.protocol.bgp4.spec.routes: 20000
#routing.protocol.ipv4.bgp4: yes
#routing.protocol.ipv4.ospf: yes
#routing.protocol.ipv4.rip: yes
#routing.protocol.ipv4.rip2: yes
#routing.protocol.ipv6.ospfv3: yes
#routing.protocol.ipv6.ripng: yes
#routing.protocol.ospf.spec.1.neighbor: 30
#routing.protocol.ospf.spec.1.routes: 20000
#routing.protocol.ospf.spec.2.neighbor: 60
#routing.protocol.ospf.spec.2.routes: 10000
#slots.expansion: 1
#slots.microsd: no
#throughput.ether: 1.5gig
#throughput.ipsec: 360meg
#throughput.l2tpv3: no
#throughput.l2tpv3-ipsec: no
#vpn.3des: yes
#vpn.des: yes
#vpn.ipsec: yes
#vpn.l2tpipsec: yes
#vpn.pptp.sites: no
#vpn.sites.config: 1000
#vpn.sites.ipsec: 1000
#vpn.sites.l2tpv3: no
#閉域網サービス.ipv4multicast: yes
#閉域網サービス.ipv6multicast: yes
#閉域網サービス.tagvlan: yes
